services:
  db:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./database/postgres/database/schema:/docker-entrypoint-initdb.d

  adminer: # For Testing ONLY - Local web-based database manager
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    command: mvn spring-boot:run
    ports:
      - "2800:2800"
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:${DB_PORT}/${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
